#Library = libft

SRCS = 	ft_isalnum.c \
						ft_isdigit.c	\
						ft_memcmp.c		\
						ft_memset.c 	\
						ft_strlcpy.c 	\
						ft_strnstr.c 	\
						ft_toupper.c 	\
						ft_atoi.c		\
						ft_isalpha.c 	\
						ft_isprint.c 	\
						ft_memcpy.c 	\
						ft_memmove.c 	\
						ft_strlcat.c 	\
						ft_strncmp.c 	\
						ft_tolower.c 	\
						ft_strchr.c 	\
						ft_strlen.c 	\
						ft_strrchr.c 	\
						ft_bzero.c 		\
						ft_isascii.c 	\
							ft_memchr.c \
							ft_calloc.c \
								ft_strdup.c \
								ft_substr.c 

CC = cc
CFLAGS = -Wall -Wextra -Werror

OBJS = $(SRCS:.c=.o)
NAME = libft.a

all: $(NAME)

$(NAME): $(OBJS)
	ar rcs $(NAME) $(OBJS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f $(OBJS)
fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re